ASP.NETCore/AspNetProject/MountainGuide/MountainGuide/Models/TouristBuilding/AllTouristBuildingViewModel.cs
using MountainGuide.Core.Services.TouristBuilding.Models;
using System.ComponentModel.DataAnnotations;

namespace MountainGuide.Models.TouristBuilding
{
    public class AllTouristBuildingViewModel
    {
        public List<TouristBuildingTypeServiceModel> BuildingTypes { get; set; } = new List<TouristBuildingTypeServiceModel>();

        public List<MountainServiceModel> Mountains { get; set; } = new List<MountainServiceModel>();

        public List<TouristBuildingServiceModel> Buildings { get; set; } = new List<TouristBuildingServiceModel>();

        [Display(Name = "Building Type")]
        public int TypeFilter { get; set; } = 0;

        [Display(Name = "Mountain")]
        public int MountainFilter { get; set; } = 0;

        public int BuildingsPerPage { get; set; } = 3;

        public int CurrentPage { get; init; } = 1;

        public int TotalBuildings { get; set; }

    }
}

ASP.NETCore/AspNetProject/MountainGuide/MountainGuide/Models/TouristBuilding/TouristBuildingDetailsViewModel.cs
#nullable disable
using MountainGuide.Core.Services.TouristBuilding.Models;
using System.ComponentModel.DataAnnotations;

namespace MountainGuide.Models.TouristBuilding
{
    public class TouristBuildingDetailsViewModel
    {
        public TouristBuildingDetailsServiceModel TouristBuilding { get; set; }

        [Required]
        [StringLength(int.MaxValue, MinimumLength = ViewConstant.CommentMinLength)]
        public string AddCommentContent { get; set; }

    }
}

ASP.NETCore/AspNetProject/MountainGuide/MountainGuide/Controllers/AnnouncementController.cs
using Microsoft.AspNetCore.Mvc;
using MountainGuide.Core.Services.Announcement.Models;
using MountainGuide.Core.Services.Contracts;
using MountainGuide.Models.Announcement;

namespace MountainGuide.Controllers
{
    public class AnnouncementController : Controller
    {
        private readonly IAnnouncementService announcementService;

        public AnnouncementController(IAnnouncementService announcementService)
        {
            this.announcementService = announcementService;
        }
        public IActionResult All(int currentPage = 1)
        {
            var queryResult = this.announcementService.GetAllAnnouncements(
                currentPage, ViewConstant.AnnouncementsPerPage);

            return View(new AllAnnouncementServiceQueryModel
            {
                CurrentPage = currentPage,
                TotalAnnouncements = queryResult.TotalAnnouncements,
                Announcements = queryResult.Announcements
            });
        }

        public IActionResult Details(int id)
        {
            var serviceModel = announcementService.GetAnnouncementDetails(id);
            
            if (serviceModel == null)
            {
                return NotFound();
            }

            return View(new AnnouncementDetailsViewModel
            {
                Announcement = serviceModel
            });
        }
    }
}

ASP.NETCore/AspNetProject/MountainGuide/MountainGuide/Controllers/CommentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MountainGuide.Core.Services.Contracts;
using MountainGuide.Infrastructure.Data.Models;
using MountainGuide.Models.Announcement;
using MountainGuide.Models.TouristBuilding;

namespace MountainGuide.Controllers
{
    public class CommentController : Controller
    {
        private readonly SignInManager<User> signInManager;
        private readonly UserManager<User> userManager;
        private readonly ICommentService commentService;


        public CommentController(
            SignInManager<User> signInManager,
            UserManager<User> userManager,
            ICommentService commentService)
        {
            this.signInManager = signInManager;
            this.userManager = userManager;
            this.commentService = commentService;
        }

        [HttpPost]
        [Authorize]
        public IActionResult AddCommentToAnnouncement(AnnouncementDetailsViewModel model)
        {
            if (!signInManager.IsSignedIn(User))
            {
                return Redirect("/Identity/Account/Login");
            }

            commentService.AddCommentToAnnouncement(model.Announcement.Id, model.AddCommentContent, userManager.GetUserId(User));

            return Redirect($"/Announcement/Details/{model.Announcement.Id}");
        }

        public IActionResult AddCommentToTouristBuilding(TouristBuildingDetailsViewModel model)
        {
            if (!signInManager.IsSignedIn(User))
            {
                return Redirect("/Identity/Account/Login");
            }

            commentService.AddCommentToTouristBuilding(model.TouristBuilding.Id, model.AddCommentContent, userManager.GetUserId(User));
            return Redirect($"/TouristBuilding/Details/{model.TouristBuilding.Id}");
        }
    }
}

ASP.NETCore/AspNetProject/MountainGuide/MountainGuide/Controllers/TouristBuildingController.cs
using Microsoft.AspNetCore.Mvc;
using MountainGuide.Core.Services.Contracts;
using MountainGuide.Core.Services.TouristBuilding.Models;
using MountainGuide.Models.TouristBuilding;

namespace MountainGuide.Controllers
{
    public class TouristBuildingController : Controller
    {
        private readonly ITouristBuildingService buildingService;

        public TouristBuildingController(
            ITouristBuildingService buildingService)
        {
            this.buildingService = buildingService;
        }
        public IActionResult All([FromQuery] AllTouristBuildingViewModel model)
        {

            model.Buildings = buildingService.GetAllBuildings(model.TypeFilter,
                model.MountainFilter,
                model.BuildingsPerPage,
                model.CurrentPage);
            model.Mountains = buildingService.GetAllMountains();
            model.BuildingTypes = buildingService.GetAllBuildingTypes();
            model.TotalBuildings = buildingService.GetAllBuildingsCount(model.TypeFilter, model.MountainFilter);

            return View(model);
        }

        public IActionResult Details(int id)
        {
            var serviceModel = buildingService.GetBuildingDetails(id);

            if (serviceModel == null)
            {
                return NotFound();
            }
            return View(new TouristBuildingDetailsViewModel
            {
                TouristBuilding = serviceModel
            }); 
        }
    }
}

ASP.NETCore/AspNetProject/MountainGuide/MountainGuide/Views/TouristBuilding/All.cshtml
@using MountainGuide.Models.TouristBuilding

@model AllTouristBuildingViewModel

@{
    ViewBag.Title = "Tourist Buildings";
}

@{
    var previousPage = Model.CurrentPage - 1;
    var nextPage = Model.CurrentPage + 1;
    if (previousPage < 1)
    {
        previousPage = 1;
    }

    var maxPage = Math.Ceiling((double)Model.TotalBuildings / ViewConstant.AnnouncementsPerPage);
}

<div class="text-center">
    <h2>Tourist Builbings:</h2>
</div>
<div class="row justify-content-center m-2 gx-5 d-flex align-items-center">
    <form method="get" class="row row-cols-1 row-cols-md-3 g-4 align-items-center">
        <div class="col">
            <label asp-for="TypeFilter"></label>
            <select asp-for="TypeFilter" class="form-select" aria-label="Default select example" style="width: 18rem;">
                <option value="0">All</option>
                @foreach (var type in Model.BuildingTypes)
                {
                    <option value="@type.Id">@type.Name</option>
                }
            </select>
        </div>
        <div class="col">
            <label asp-for="MountainFilter"></label>
            <select asp-for="MountainFilter" class="form-select" aria-label="Default select example" style="width: 18rem;">
                <option value="0">All</option>
                @foreach (var mountain in Model.Mountains)
                {
                    <option value="@mountain.Id">@mountain.Name</option>
                }
            </select>
        </div>
        <div class="col">
            <button class="btn btn-secondary" type="submit">
                Search
            </button>
        </div>
    </form>
</div>

<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-end">
        <li class="page-item @(Model.CurrentPage == 1 ? " disabled" : string.Empty)">
            <a class="page-link btn"
               asp-controller="TouristBuilding"
               asp-action="All"
               asp-route-currentPage="@previousPage"
               asp-route-typeFilter="@Model.TypeFilter"
               asp-route-mountainFilter="@Model.MountainFilter">Previous</a>
        </li>
        @for (int i = 1; i <= maxPage; i++)
        {
            <li class="page-item">
                <a class="page-link btn"
               asp-controller="TouristBuilding"
               asp-action="All"
               asp-route-currentPage="@i"
               asp-route-typeFilter="@Model.TypeFilter"
               asp-route-mountainFilter="@Model.MountainFilter">@i</a>
            </li>
        }
        @{
            var shouldButtonBeDisabled = Model.CurrentPage == maxPage ||
                !Model.Buildings.Any();
        }

        <li class="page-item @(shouldButtonBeDisabled ? " disabled" : string.Empty)">
            <a class="page-link btn"
               asp-controller="TouristBuilding"
               asp-action="All"
               asp-route-currentPage="@nextPage"
               asp-route-typeFilter="@Model.TypeFilter"
               asp-route-mountainFilter="@Model.MountainFilter">Next</a>
        </li>
    </ul>
</nav>
@if (!Model.Buildings.Any())
{
    <h2 class="text-center">No buildings found by the given criteria!</h2>
}
else
{
    <div class="row row-cols-1 row-cols-md-3 g-4">
        @foreach (var building in Model.Buildings)
        {
        <div class="col">
            <div class="card h-100 rounded-2 shadow">
                <img src="@building.FrontImageUrl" class="card-img-top" alt="@building.Name @building.MountainName">
                <div class="card-body">
                    <h5 class="card-title">@building.Name @Model.BuildingTypes.Where(t => t.Id == building.TouristBuildingTypeId).First().Name</h5>
                    <p class="card-text">@building.Description</p>
                </div>
                <div class="card-footer">
                    Announcements: @building.AnnouncementsCount Likes: @building.LikesCount Comments: @building.CommentsCount
                    <a asp-controller="TouristBuilding" asp-action="Details" asp-route-id="@building.Id" class="card-link">Details</a>
                </div>
            </div>
        </div>
        }
    </div>
}

ASP.NETCore/AspNetProject/MountainGuide/MountainGuide/Views/TouristBuilding/Details.cshtml
@using MountainGuide.Models.TouristBuilding
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

@model TouristBuildingDetailsViewModel
@{
    ViewData["Title"] = "Tourist Building Details";
}

<div class="row justify-content-center gx-5 d-flex align-items-center">
    <div class="card m-4 p-1 rounded-2 shadow" style="width: 40rem;">
        <div class="card-body">
            <h5 class="card-title">@Model.TouristBuilding.Name @Model.TouristBuilding.TouristBuildingTypeName</h5>
            <h6 class="card-subtitle mb-2 text-muted">
                <a asp-controller="Mountain" asp-action="Details" asp-route-id="@Model.TouristBuilding.MountainId">@Model.TouristBuilding.MountainName</a>
            </h6>
            <p class="card-text">@Model.TouristBuilding.Description</p>
            <p>Altitude: @Model.TouristBuilding.Altitude</p>
            <p>Capacity: @Model.TouristBuilding.Capacity</p>
            <p>Phone number: @Model.TouristBuilding.PhoneNumber</p>
            <p>Coordinate: @Model.TouristBuilding.Latitude, @Model.TouristBuilding.Longitude</p>
            <p>Tourist Association: <a asp-controller="TouristAssociation" asp-action="Details" asp-route-id="@Model.TouristBuilding.TouristAssociationId">@Model.TouristBuilding.TouristAssociationName</a></p>
            <div class="align-middle fst-italic float-end">
                Announcements: @Model.TouristBuilding.Announcements.Count() Comments: @Model.TouristBuilding.Comments.Count()
                <i class="fa-solid fa-thumbs-up text-info"> @Model.TouristBuilding.LikesCount</i>
            </div>
        </div>
    </div>
</div>
<h6 class="text-center">Location</h6>
<div class="row justify-content-center gx-5 d-flex align-items-center">
    <div class="card m-4 p-1 rounded-2 shadow" style="width: 40rem;">
        <div id="map" style="height: 39.5rem; width: 39.5rem;"></div>
    </div>
</div>
<h6 class="text-center">Gallery</h6>

<div class="row justify-content-center m-4 gx-5 d-flex align-items-center">
    <div class="galleria">
        @foreach (var img in @Model.TouristBuilding.Images)
        {
            <a href="@img.ImageUrl">
                <img src="@img.ImageUrl" alt="@img.Description">
            </a>
        }
    </div>
</div>
<h6 class="text-center">Announcements</h6>
<div class="row justify-content-center gx-5 d-flex align-items-center">
    @if (!Model.TouristBuilding.Announcements.Any())
    {
        <p class="text-center">There are no аnnouncement yet.</p>
    }
    else
    {
        @foreach (var ad in @Model.TouristBuilding.Announcements)
        {
            <div class="card m-4 p-1 rounded-2 shadow" style="width: 35rem;">
                <div class="card-body">
                    <h5 class="card-title"><a asp-controller="Announcement" asp-action="Details" asp-route-id="@ad.Id">@ad.Title</a></h5>
                    <h6 class="card-subtitle mb-2 text-muted">@ad.DateTimeAdded</h6>
                    <p class="card-text">@ad.Content</p>
                    <div class="align-middle fst-italic float-end">
                        <i class="fa-solid fa-thumbs-up text-info"> @ad.LikesCount</i>
                    </div>
                </div>
            </div>
        }
    }
</div>
<div class="row justify-content-center gx-5 d-flex align-items-center">
    <h6 class="text-center">Comments:</h6>
    @if (!Model.TouristBuilding.Comments.Any())
    {
        <p class="text-center">There are no comments for this building yet.</p>
    }
    else
    {
        <div class="card m-4 p-1 rounded-2 shadow" style="width: 35rem;">
            <div class="card-body">
                <ul class="list-group list-group-flush">
                    @foreach (var comm in @Model.TouristBuilding.Comments)
                    {
                        <li class="list-group-item">
                            <p class="text-info">@comm.UserName <span class="text-secondary">@comm.DateTimeAdded</span></p>
                            <p class="card-text">@comm.Content</p>
                            <div class="align-middle fst-italic float-end">
                                <i class="fa-solid fa-thumbs-up text-info"> @comm.LikesCount</i>
                            </div>
                        </li>
                    }
                </ul>
            </div>
        </div>
    }
</div>
<div class="row justify-content-center gx-5 d-flex align-items-center">
    @if (SignInManager.IsSignedIn(User))
    {
        <p class="text-center">Add comment:</p>
        <div class="card m-4 p-1 rounded-2 shadow" style="width: 35rem;">
            <form method="post">
                <div class="form-group">
                    <textarea asp-for="AddCommentContent" rows="4" class="form-control" placeholder="Add your comment here..."></textarea>
                    <span asp-validation-for="AddCommentContent" class="small text-danger"></span>
                </div>
                <input asp-for="TouristBuilding.Id" value="@Model.TouristBuilding.Id" type="hidden" class="form-control">
                <input asp-controller="Comment" asp-action="AddCommentToTouristBuilding" class="btn btn-primary mt-3 float-end" type="submit" value="Add" />
            </form>
        </div>
    }
</div>

@section Scripts {
<script>
    map(@Model.TouristBuilding.Latitude, @Model.TouristBuilding.Longitude);
</script>
<script>
    galeria();
</script>
<script>
    <partial name="_ValidationScriptsPartial" />
</script>
}